import org.gradle.api.plugins.JavaPluginExtension

plugins {
    id 'base'
}

allprojects {
    group = project.findProperty('maven_group') ?: 'me.datsuns.simplecoordinate'
    version = project.findProperty('mod_version') ?: '0.0.0'
}

subprojects {
    repositories {
        maven {
            name = "Fabric"
            url = "https://maven.fabricmc.net/"
        }
        maven {
            name = "NeoForge"
            url = "https://maven.neoforged.net/releases"
        }
        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/releases/"
        }
        maven {
            url = "https://maven.shedaniel.me/"
        }
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 21
    }

    pluginManager.withPlugin('java') {
        extensions.configure(JavaPluginExtension) {
            it.withSourcesJar()
            it.setSourceCompatibility(JavaVersion.VERSION_21)
            it.setTargetCompatibility(JavaVersion.VERSION_21)
        }
    }
}
