# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.4.0
maven_group=me.datsuns.simplecoordinate
archives_base_name=simple-coordinates

# Modrinth
modrinth_project_id = OT4jnFfV

# NeoForge Properties
mod_id=simplecoordinates
mod_name=Simple Coordinates
mod_license=CC0-1.0
mod_authors=datsuns
mod_description=simple display for Coordinates on HUD.
minecraft_version_range=[26.1.1]
neo_version=26.1.1.6-beta
neoforge_moddev_version=2.0.141

# Dependencies
fabric_api_version=0.145.3+26.1.1
modmenu_version=18.0.0-alpha.8
cloth_config_api_version=26.1.154
